title: Andrea Rabbaglietti's Blog
description: >
  Articles and cool stuff about personal projects, scalability, cloud architectures, and distributed system
url: "https://rabbagliettiandrea.github.io"
exclude: []
permalink: /:title/

# Author Settings
author: Andrea Rabbaglietti
author-img: andrea-rabbaglietti.jpg
author-img-meta: andrea-rabbaglietti-bw.jpg
about-author: >
  I really love cloud architectures, distributed systems,
  big-data crunching, caching optimization and scalability.
social-github: rabbagliettiandrea
social-linkedin: andrearabbaglietti
social-email: rabbagliettiandrea@gmail.com

# Build Settings
markdown: redcarpet
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Pagination Settings
paginate: 100
paginate_path: "/page/:num"
